### ISSUE TITLE
Projects have incorrect roman numeral spacing

### ISSUE THREAD

**Issue by xdesro** [jdminnickjr/personal-site#13]
You've put `margin-right` on every roman numeral in the projects section, even on large screens, but for the even-numbered projects, this makes the layout wrong. 

<img width="688" alt="JD_Minnick_Developer" src="https://user-images.githubusercontent.com/13542610/101403699-d5e70580-3892-11eb-8dbd-fa1edbcb44cb.png">

**Comment by jdminnickjr** [comment]
The III numeral gets pulled under the text when I remove it
