### ISSUE TITLE
"JD Minnick" has wrong font-size on mobile

### ISSUE THREAD

**Issue by xdesro** [jdminnickjr/personal-site#14]
I've got it set to like 70px in the comp — try and make sure it's as close to this as possible.

**Comment by jdminnickjr** [comment]
This is as close as it can be without breaking into two lines

**Comment by xdesro** [comment]
Hmm, I'm able to move it up quite a bit. Maybe try a variable size like `16vw` on small screen sizes?

**Comment by jdminnickjr** [comment]
So i have tweaked this but i forgot to tag this one in the message

**Comment by xdesro** [comment]
Sounds good to me! Closing!
