### ISSUE TITLE
Timeline broken past 1440px

### ISSUE THREAD

**Issue by leviboenish** [jdminnickjr/personal-site#20]
Timeline gets a little wonky on larger screens 
![image](https://user-images.githubusercontent.com/31256961/101516064-4564ff80-393c-11eb-89e8-0d43845e578e.png)

**Comment by xdesro** [comment]
Couple of tips for fixing this, which is related to #6:

- [x] Don't use percentages...like nearly ever? I can't recall the last time I actually needed a percentage.
- [x] There's a max-width on both the timeline and the timeline children, but you probably only need it on the parent timeline! I would clear it on the children and then....
- [x] Up the max-width on the timeline to ~22rem (this is a design nitpick, it's not 1:1 to the design. Thanks for bein' flexible)

**Comment by leviboenish** [comment]
this is no longer broken
