### ISSUE TITLE
Tarot hover state

### ISSUE THREAD

**Issue by leviboenish** [jdminnickjr/personal-site#3]
My brain wants like a slight hover animation on the tarot cards (like the one I'm hovering 'lifts' a little) Take or leave this one just thought it might be sick

**Comment by leviboenish** [comment]
when you hover off they snap back which is a tiny bit jarring, might wanna add that transition to either the base element or the hover (whichever doesn't have it) so that it shrinks at the same rate as the hover (If that doesn't make sense yell at me)

**Comment by xdesro** [comment]
Also, don't animate `width` or `height` or any box properties — this is a bit nuanced, but they require a repaint operation by the browser, so they're very render expensive and often janky (the way the hover forces every other child to move). If you need to change the size of an element, `transform: scale()` is gonna be the hardware-accelerated solution to this.

**Comment by jdminnickjr** [comment]
I did some digging and couldnt really find what i needed to smooth that transition off hover

**Comment by xdesro** [comment]
This new solution is infinitely better. I'm in favor of closing — @leviboenish ?

**Comment by leviboenish** [comment]
Hell yeah BRÖTHER
