### ISSUE TITLE
Overlay texture not in repo

### ISSUE THREAD

**Issue by xdesro** [jdminnickjr/personal-site#4]
There's a 404 error because you added the CSS for the overlay texture but never actually added the image to the repo in git.

<img width="880" alt="Developer_Tools_—_JD_Minnick_Developer_—_https___eager-jennings-01172b_netlify_app__and_New_Issue_·_jdminnickjr_personal-site" src="https://user-images.githubusercontent.com/13542610/101401144-2492a080-388f-11eb-9e8b-b72d18cf145d.png">

**Comment by jdminnickjr** [comment]
OK so how do I go about that?

**Comment by xdesro** [comment]
`git add` and `git commit` it, the same way you'd add any other file to the repo
