### ISSUE TITLE
Timeline needs some layout and type love

### ISSUE THREAD

**Issue by xdesro** [jdminnickjr/personal-site#6]
## List Items

- [x] The list items need to have a maximum width of around 266px on desktop. Right now they just kinda go as far as they can. I'd recommend a `max-width` declaration, but it'll require you tweak the parent CSS to make sure everything stays centered.
- [x] List items need to be set in "GT Super Text", instead of "GT Super Display". 
- [x] The distance between the date and the text below should only be 24px or 1.5rem. Currently it is much larger than that.

## Dates
- [x] Dates need to have about 25% letter spacing. You can do this with `letter-spacing: .25em;`. 

## Roman Numerals
- [x] Roman numerals need to be set in "GT Super Display".

**Comment by jdminnickjr** [comment]
So the Grid gap is giving it applying to the top as well as the side, is there a way to remove it from just the top? re: #6.3

**Comment by xdesro** [comment]
Closing this but make sure you take a look at #20!
